name: Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test

      web:
        build: .
        ports:
          - 3000:3000
        env:
          TZ: Asia/Tokyo
        volumes:
          - .:/app
          - bundle_data:/usr/local/bundle:cached
          - node_modules:/app/node_modules

    steps:
      - uses: actions/checkout@v1

      # Rubyセットアップ
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      # Node.jsとYarnのセットアップ
      - name: Set up Node.js and Yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/yarn.gpg > /dev/null
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          curl -sL https://deb.nodesource.com/setup_18.x | sudo bash -
          sudo apt update
          sudo apt install -y yarn nodejs

      # Chromeインストール
      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/google-chrome.gpg > /dev/null
          echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update -y
          sudo apt install -y google-chrome-stable

      # ビルドとテスト
      - name: Build
        run: |
          bundle install --jobs=4
          bin/rails db:setup assets:precompile

      - name: Run tests
        run: |
          bin/rails test
