name: Check RuboCop and Run Tests
on:
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    needs: rubocop
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Precompile assets
        run: bin/rails assets:precompile RAILS_ENV=test

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..30}; do
            if pg_isready -U postgres; then
              echo "Postgres is ready!"
              break
            fi
            echo "Waiting for Postgres..."
            sleep 1
          done

      - name: Create database
        run: |
          cp config/database.yml.ci config/database.yml
          RAILS_ENV=test bin/rails db:create db:schema:load

      - name: Run Minitest
        run: bin/rails test
