name: Check RuboCop and Run Tests
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    needs: rubocop
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: bundle install

      - name: Wait for Postgres to be ready
        run: sleep 10

      - name: Create database
        run: |
          cp config/database.yml.ci config/database.yml
          RAILS_ENV=test bin/rails db:create db:schema:load

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run Minitest
        run: bin/rails test
